### ISSUE TITLE
Support for DHKEM(P-256, HKDF-SHA256)

### ISSUE THREAD

**Issue by tomtau** [rozbb/rust-hpke#1]
Some options:

### ring
https://briansmith.org/rustdoc/ring/agreement/index.html

pros:
1. high-level APIs
2. based on BoringSSL / verified Fiat-Crypto primitives

cons:
1. custom traits not that compatible with the current code:

- custom rand: https://briansmith.org/rustdoc/ring/rand/index.html
- ECDH isn't directly exposed: https://briansmith.org/rustdoc/ring/agreement/fn.agree_ephemeral.html -- I guess one could still misuse it by passing identity function to "kdf" and then doing kdf later
- ...

2. extra code bloat / overlap -- X25519, AEAD, KDF...

Perhaps the way around may be to have a "resolver" similar to snow: https://github.com/mcginty/snow/blob/master/src/resolvers/mod.rs

### fiat-crypto
https://docs.rs/fiat-crypto/0.1.4/fiat_crypto/p256_64/index.html

pros:
1. verified fast primitives

cons:
1. low level primitives 
2. extra unneeded curves

### p256
https://docs.rs/p256/0.2.0/p256/arithmetic/index.html

pros:
1. traits nicely fitting with GenericArray etc.
2. no unneeded code

cons:
1. low level primitives
2. early stage / not battle-tested -- not formally verified and potentially slow in the current version

**Comment by rozbb** [comment]
Thanks for this! As far as I can tell, `fiat-crypto` implements only field arithmetic and no curve operations, so that's certainly out. And I'd like to avoid using something as big as `ring` if I can. `p256` is certainly new, but I trust the people making it and I hope it'll get reviewed soon. I also hope they'll continue their implementation and get `p521` implemented soon too.

So yeah, `p256` it is.

**Comment by rozbb** [comment]
What I am even more curious about is why there isn't `x448` support anywhere
