### ISSUE TITLE
Is the `Kdf` embed in `Kem` should be the same with the outside `Kdf`?

### ISSUE THREAD

**Issue by yihuang** [rozbb/rust-hpke#4]
Many functions generic over both `Kdf` and `Kem`, I wonder is it supposed that the `Kdf` should be the same with `Kem::Kdf`?

**Comment by rozbb** [comment]
`Kem` is an arbitrary key encapsulation mechanism. Currently, it's implemented with an underlying key exchange mechanism + KDF. The spec currently allows for `Kem::Kdf` to be different from the outermost `Kdf`. I demonstrate this in `examples/client_server.rs`.

But your point is well taken, and having 2 `Kdf`s visible is confusing. So I removed `Kem::Kdf` from the documentation, since there's no need for it to be there in the first place. Does that work for you?

**Comment by yihuang** [comment]
yes, that more clear to me, thanks.
