### ISSUE TITLE
Why not RSA?

### ISSUE THREAD

**Issue by JonathanWilbur** [rozbb/rust-hpke#56]
Forgive my ignorance. I am not a cryptographer by trade. But I believe RSA could be used as a KEM in the abstract. I noticed that RFC 9180 does not list it as a registered KEM. I thought this was weird, since RSA is by far the most common public key type in X.509 PKI. Just wondering if this could be implemented at all.

**Comment by tarcieri** [comment]
Speaking as a maintainer of the `rsa` crate, it's very, very difficult to implement RSA in constant-time. See the recent [Marvin Attack](https://people.redhat.com/~hkario/marvin/) (which the `rsa` crate is still vulnerable to, see https://github.com/RustCrypto/RSA/issues/19).

Elliptic curves, especially with modern complete formulas, are significantly easier to implement in constant-time.

**Comment by rozbb** [comment]
Totally valid question. Indeed, RSA would be a perfectly valid key encapsulation mechanism for HPKE. The reason it's not implemented here is simply because nobody (to my knowledge) has drafted a proposal for a protocol extension.

If someone did, we could reasonably implement it and keep it in an unstable branch (like the current k256 and xyber branches) until it's finalized. Does that answer the question?

**Comment by JonathanWilbur** [comment]
Yes it does. Thank you! Closing.
