### ISSUE TITLE
Kem::derive_keypair produces different private keys in cisco/go-hpke from same ikm

### ISSUE THREAD

**Issue by picowar** [rozbb/rust-hpke#6]
The function [`Kem::derive_keypair`](https://docs.rs/hpke/0.3.1/hpke/kem/trait.Kem.html#method.derive_keypair) produces a slightly different private key using this implementation, as opposed to the [cisco/go-hpke DeriveKeyPair](https://github.com/cisco/go-hpke/blob/9e7d3e90b7c3a5b08f3099c49520c587568c77d6/crypto.go#L387) function.

This is for the `X25519` curve.

I tested both with `ikm`s of two different sizes, 32 bytes (as is mentioned in the [requirements for X25519](https://docs.rs/hpke/0.3.1/hpke/kem/trait.Kem.html#requirements)) and 16 bytes.

Here is the Rust code:
```rust
use hpke::{
    kem::X25519HkdfSha256,
    Serializable, Kem as KemTrait, 
};

pub type Kem = X25519HkdfSha256;
pub type Kex = <Kem as KemTrait>::Kex;

fn main() {
    let ikm = vec![135u8, 19, 137, 168, 114, 113, 48, 151, 78, 62, 179, 238, 82, 141, 68, 10, 135, 19, 137, 168, 114, 113, 48, 151, 78, 62, 179, 238, 82, 141, 68, 10];

    let (secret_key, public_key) = Kem::derive_keypair(&ikm);
    println!("Secret key: {:?}", secret_key.to_bytes());
    println!("Public key: {:?}", public_key.to_bytes());
}
```

Output is:
```shell
Secret key: [176, 38, 135, 117, 71, 0, 191, 112, 249, 158, 100, 171, 140, 16, 126, 120, 10, 93, 91, 242, 36, 126, 81, 188, 74, 167, 64, 40, 152, 110, 81, 82]
Public key: [85, 232, 242, 165, 106, 24, 255, 130, 68, 60, 26, 190, 158, 252, 198, 107, 68, 197, 145, 43, 231, 29, 133, 203, 57, 25, 1, 10, 123, 95, 39, 56]
```

Here is the go code:
```go
package main

import (
	"fmt"
	"github.com/cisco/go-hpke"
)

func main() {
	ikm := []byte{135, 19, 137, 168, 114, 113, 48, 151, 78, 62, 179, 238, 82, 141, 68, 10, 135, 19, 137, 168, 114, 113, 48, 151, 78, 62, 179, 238, 82, 141, 68, 10}

	kemID := hpke.DHKEM_X25519
	kdfID := hpke.KDF_HKDF_SHA256
	aeadID := hpke.AEAD_AESGCM128
	suite, err := hpke.AssembleCipherSuite(kemID, kdfID, aeadID)
	if err != nil { return }

	secret_key, public_key, err := suite.KEM.DeriveKeyPair(ikm)
	if err != nil { return }

	fmt.Printf("Secret Key: %v\n", suite.KEM.SerializePrivate(secret_key))
	fmt.Printf("Public Key: %v\n", suite.KEM.Serialize(public_key))
}
```

And the output:
```shell
Secret Key: [176 38 135 117 71 0 191 112 249 158 100 171 140 16 126 120 10 93 91 242 36 126 81 188 74 167 64 40 152 110 81 18]
Public Key: [85 232 242 165 106 24 255 130 68 60 26 190 158 252 198 107 68 197 145 43 231 29 133 203 57 25 1 10 123 95 39 56]
```

You will notice that the public keys are the same, but the secret key has a 1 byte difference at the very last byte, 82 vs 18.

**Rust** 
Secret key: [176, 38, 135, 117, 71, 0, 191, 112, 249, 158, 100, 171, 140, 16, 126, 120, 10, 93, 91, 242, 36, 126, 81, 188, 74, 167, 64, 40, 152, 110, 81, **82**]

**Go**
Secret Key: [176 38 135 117 71 0 191 112 249 158 100 171 140 16 126 120 10 93 91 242 36 126 81 188 74 167 64 40 152 110 81 **18**]

When I used the 16 byte `ikm` below (though it is not recommended to use 16 bytes)
```rust
let ikm = vec![135u8, 19, 137, 168, 114, 113, 48, 151, 78, 62, 179, 238, 82, 141, 68, 10];
```
The first byte of the private keys is different, 184 vs 188.

**Rust**
Secret key: [**184**, 86, 138, 107, 61, 96, 200, 230, 79, 250, 160, 108, 161, 64, 127, 13, 117, 224, 246, 153, 25, 21, 167, 231, 103, 147, 143, 86, 213, 177, 44, 82]

**Go**
Secret Key: [**188** 86 138 107 61 96 200 230 79 250 160 108 161 64 127 13 117 224 246 153 25 21 167 231 103 147 143 86 213 177 44 82]

**Comment by rozbb** [comment]
Hmm, so this isn't ordinarily a problem, but it actually might point to another problem in go-hpke.

The cause of the difference is that rust-hpke [clamps](https://docs.rs/x25519-dalek/1.1.0/src/x25519_dalek/x25519.rs.html#140-145) its X25519 secret keys before storing them, while go-hpke [does not.](https://github.com/cisco/go-hpke/blob/9e7d3e90b7c3a5b08f3099c49520c587568c77d6/crypto.go#L435)

_Clamping_ essentially canonicalizes scalar values for non-prime-order curves. Importantly, **a scalar is equivalent (as a secret key) to its clamped version**. In X25519, clamping is defined as
```rust
fn clamp_scalar(mut scalar: [u8; 32]) -> Scalar {
    scalar[0] &= 248;
    scalar[31] &= 127;
    scalar[31] |= 64;
    Scalar::from_bits(scalar)
}
```
If you check the secret values, you'll see that `(18 & 127) | 64 = 82` (explaining the first difference), and `188 & 248 = 184` (explaining the second difference).

So the reason why clamping isn't important in HPKE is because 1. the secret keys are functionally equivalent (resulting in the same pubkeys), and 2. the spec doesn't rely on any sort of canonical representation of secret keys. In fact, the spec doesn't define the byte representation of secret keys at all (there's no Serialize/Deserialize for secret keys).

**However** I think you've caught something much more important: because there is no clamping and no zero checks anywhere in the Go code (as far as I can tell), go-hpke is not spec compliant. I'm gonna ask the maintainer if this is the case. Thanks for bringing this up!
